openapi: 3.0.1
info:
  title: checkout-demo-php
  description: checkout-demo-php
  x-cortex-tag: checkout-demo-php
  x-cortex-git:
    github:
      repository: xendit/checkout-demo-php
  x-cortex-owners:
  - type: GROUP
    name: xendit/api-full-time
  - email: sherwyn@xendit.co
    type: EMAIL
  x-cortex-service-groups:
  - sherwyn@xendit.co
  - P3
  - Fundamentals
